// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-dzN6z_GdPEGcfJyeZL0syUDVHIvtTHc',
    appId: '1:80499955330:web:a13840d45e205382e9c69b',
    messagingSenderId: '80499955330',
    projectId: 'hyperdynamics-loyalty',
    authDomain: 'hyperdynamics-loyalty.firebaseapp.com',
    storageBucket: 'hyperdynamics-loyalty.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVD1PaCwj40xqz54SNEgPEvDNkTEGAUc',
    appId: '1:80499955330:android:b3abe275e9541fd4e9c69b',
    messagingSenderId: '80499955330',
    projectId: 'hyperdynamics-loyalty',
    storageBucket: 'hyperdynamics-loyalty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKP6zWmLfKfqrtg7zF2Idbl4oKQQNOv6A',
    appId: '1:80499955330:ios:29b9971cb32c5714e9c69b',
    messagingSenderId: '80499955330',
    projectId: 'hyperdynamics-loyalty',
    storageBucket: 'hyperdynamics-loyalty.firebasestorage.app',
    iosBundleId: 'com.hyperdynamics.loyaltyManager',
  );
}
